spring:
  application:
    name: trading-journal-service
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  #    show-sql: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/journal?serverTimezone=UTC}
    username: ${DB_USER:journaluser}
    password: ${DB_PASS:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

front-end-url: http://localhost:4200

server:
  error:
    path: /error

jwt:
  secret: ${JWT_SECRET:72357538782F413F4428472B4B6250645367566B597033733676397924422645}
  expiration: ${ACCESS_JWT:43200000} #12 hours
  refresh-token:
    expiration: ${REFRESH_JWT:86400000} # 1 day

logging:
  file:
    name: logs/trading-journal-app.log
  level:
    root: INFO
#    org.springframework.web: INFO
#    org.springframework.controllers: INFO
#    org.hibernate: DEBUG

debug: false
