spring:
  application:
    name: trading-journal-service
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
#    show-sql: true
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/journal?serverTimezone=UTC}
    username: ${DB_USER:journaluser}
    password: ${DB_PASS:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver



server:
  error:
    path: /error

jwt:
  secret: ${JWT_SECRET:72357538782F413F4428472B4B6250645367566B597033733676397924422645}
  expiration: 86400000 #30000 #300000 #5 minutes
  refresh-token:
    expiration: 86400000 # 1 day


logging:
  level:
    root: INFO
  #      org.springframework.web: INFO
  #      org.springframework.controllers: INFO
  #      org.hibernate: DEBUG
  file:
    name: logs/trading-journal-app.log

debug: false